name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      uses: pguyot/arm-runner-action@v2
      with:
        base-image: raspios_lite_arm64:latest
        commands: |
            docker build . --file Dockerfile --tag docker-shinyverse-arm:$(date +%s)
